name: Build and test

on: [push, pull_request]

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup RabbitMQ
        uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: 3.8.9

      - name: Install code
        run: |
          pip install .[testing,pre-commit]

      - name: Test code
        run: |
          pytest -s .

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup RabbitMQ
        uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: 3.8.9

      - name: Install code
        run: |
          pip install .[pre-commit]

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
