name: Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8
        uses: actions/python@v2
        with:
          python-version: 3.8

      - name: Install code
        run: |
          pip install .[test]

      - name: Test
        run: |
          pytest . -s
