name: Build and test

on: [push, pull_request]

jobs:

  build-and-test:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup python 3.8
      uses: actions/python@v2
      with:
        python-version: 3.8

    - name: Install code
      run: |
        pip install .[testing]

    - name: Test code
      run: |
        pytest -s .
